services:
  api:
    build: 
      context: ./backend
    container_name: backend-api
    ports:
      - "3100:3100"
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
    working_dir: /app
    env_file:
      - ./backend/.env
    depends_on:
      - db
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"


  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=reservas
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/posgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    depends_on:
      - db
  
  frontend:
    build:
      context: ./frontend
    container_name: frontend-app
    ports:
    - "3000:3000"
    volumes:
    - ./frontend:/app
    - /app/node_modules
    environment:
    - NODE_ENV=development
    command: npm run dev



volumes:
    pgdata:
